apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: market_data
    user: admin
    password: tradefan123
    editable: true
    jsonData:
      version: Flux
      organization: tradefan
      defaultBucket: market_data
      tlsSkipVerify: true
    secureJsonData:
      token: tradefan-super-secret-auth-token
