# 日志系统配置
logging:
  version: 1
  disable_existing_loggers: false
  
  # 格式化器
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
      
    detailed:
      format: '%(asctime)s [%(levelname)s] %(name)s [%(filename)s:%(lineno)d] %(funcName)s(): %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
      
    json:
      format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}'
      datefmt: '%Y-%m-%dT%H:%M:%S'
      
  # 处理器
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
      
    file_general:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: detailed
      filename: logs/trading.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: utf8
      
    file_error:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: detailed
      filename: logs/error.log
      maxBytes: 10485760  # 10MB
      backupCount: 10
      encoding: utf8
      
    file_trading:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/trading_activity.log
      maxBytes: 20971520  # 20MB
      backupCount: 10
      encoding: utf8
      
    file_performance:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/performance.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: utf8
      
  # 日志器配置
  loggers:
    # 根日志器
    root:
      level: INFO
      handlers: [console, file_general, file_error]
      
    # 交易相关日志
    trading:
      level: INFO
      handlers: [file_trading]
      propagate: false
      
    # 策略日志
    strategies:
      level: INFO
      handlers: [file_general]
      propagate: true
      
    # 数据源日志
    data:
      level: INFO
      handlers: [file_general]
      propagate: true
      
    # API日志
    api:
      level: WARNING
      handlers: [file_general, file_error]
      propagate: true
      
    # 性能日志
    performance:
      level: INFO
      handlers: [file_performance]
      propagate: false
      
    # 告警日志
    alerts:
      level: INFO
      handlers: [console, file_general]
      propagate: true
      
    # 框架日志
    framework:
      level: INFO
      handlers: [file_general]
      propagate: true
      
    # 核心系统日志
    core:
      level: INFO
      handlers: [file_general]
      propagate: true
      
    # 监控日志
    monitoring:
      level: INFO
      handlers: [file_general]
      propagate: true
      
  # 根级别设置
  root:
    level: INFO
    handlers: [console, file_general]

# 环境特定配置
environments:
  development:
    console_level: DEBUG
    file_level: DEBUG
    
  testing:
    console_level: WARNING
    file_level: INFO
    disable_file_logging: true
    
  production:
    console_level: WARNING
    file_level: INFO
    enable_json_logging: true