# TradeFan 生产环境配置
# ⚠️ 真实资金交易 - 请谨慎操作

# API配置 - 生产环境
api:
  exchange: "binance"
  environment: "production"  # 生产环境
  # 安全起见，API密钥通过环境变量读取
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  base_url: "https://api.binance.com"  # 生产环境URL
  
# 生产交易配置
trading:
  initial_capital: 500  # $500 初始资金
  max_positions: 2      # 限制同时持仓数量
  position_size_mode: "fixed_dollar"  # 固定美元金额
  position_size: 50     # 每次交易$50
  
  # 交易对配置 - 保守选择
  symbols:
    - symbol: "BTCUSDT"
      enabled: true
      allocation: 0.5     # 50%资金分配
      min_trade_size: 25  # 最小交易金额$25
    - symbol: "ETHUSDT" 
      enabled: true
      allocation: 0.3     # 30%资金分配
      min_trade_size: 20  # 最小交易金额$20
    - symbol: "BNBUSDT"
      enabled: false      # 暂时禁用，降低风险
      allocation: 0.2
      min_trade_size: 15
      
  # 时间框架 - 保守策略
  timeframes:
    - "15m"  # 主要时间框架
    - "1h"   # 趋势确认

# 严格风险控制 - 生产环境
risk_control:
  # 基础风险参数
  max_risk_per_trade: 0.02      # 2%单笔最大风险
  max_daily_loss: 0.05          # 5%日最大亏损
  max_total_loss: 0.15          # 15%总最大亏损 ($75)
  max_daily_trades: 8           # 日最大交易次数
  
  # 止损止盈设置
  stop_loss_atr_multiplier: 1.5 # 保守止损
  take_profit_ratio: 2.5        # 2.5:1盈亏比
  max_position_time_hours: 6    # 6小时强制平仓
  
  # 紧急保护
  emergency_stop_loss: 0.10     # 10%紧急止损
  circuit_breaker: true         # 启用熔断机制
  max_consecutive_losses: 3     # 连续亏损3次暂停

# 策略配置 - 保守参数
strategies:
  # 主策略：趋势跟随（保守）
  trend_following:
    enabled: true
    weight: 0.7
    parameters:
      ema_periods: [21, 55, 200]
      adx_period: 14
      adx_threshold: 30        # 提高阈值，更严格
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      rsi_period: 14
      rsi_oversold: 25         # 更保守的超卖线
      rsi_overbought: 75       # 更保守的超买线
      
  # 辅助策略：短线交易（限制使用）
  scalping:
    enabled: true
    weight: 0.3
    parameters:
      ema_fast: 8
      ema_medium: 21
      ema_slow: 55
      bb_period: 20
      bb_std: 2.5            # 增加标准差，减少信号
      volume_threshold: 1.5   # 增加成交量要求

# 监控和告警
monitoring:
  log_level: "INFO"
  save_all_trades: true
  real_time_monitoring: true
  
  # 告警设置
  alerts:
    enabled: true
    loss_threshold: 0.03      # 3%亏损告警
    profit_threshold: 0.05    # 5%盈利告警
    consecutive_losses: 2     # 连续2次亏损告警
    
  # 报告设置
  reporting:
    daily_report: true
    trade_summary: true
    performance_analysis: true

# 安全设置
security:
  ip_whitelist: []            # 如需要，添加IP白名单
  rate_limiting: true         # 启用请求频率限制
  order_validation: true      # 启用订单验证
  balance_check: true         # 启用余额检查
  
# 生产环境特殊设置
production:
  paper_trading: false        # 关闭模拟交易
  confirm_trades: true        # 交易前确认
  backup_enabled: true        # 启用数据备份
  health_check_interval: 60   # 60秒健康检查
  auto_restart: false         # 禁用自动重启，需人工干预
