# 短线交易系统配置文件
# Scalping Trading System Configuration

# 基础交易配置
trading:
  # 交易对配置
  symbols:
    - symbol: "BTC/USDT"
      enabled: true
      min_volume: 1000000  # 最小24小时成交量
      max_spread: 0.001    # 最大买卖价差
    - symbol: "ETH/USDT"
      enabled: true
      min_volume: 500000
      max_spread: 0.001
    - symbol: "BNB/USDT"
      enabled: true
      min_volume: 100000
      max_spread: 0.002
    - symbol: "SOL/USDT"
      enabled: false
      min_volume: 50000
      max_spread: 0.002
  
  # 时间框架配置
  timeframes:
    - timeframe: "5m"
      enabled: true
      priority: 1          # 优先级 (1-5)
      check_interval: 5    # 检查间隔(秒)
    - timeframe: "15m"
      enabled: true
      priority: 2
      check_interval: 15
    - timeframe: "30m"
      enabled: true
      priority: 3
      check_interval: 30
    - timeframe: "1h"
      enabled: true
      priority: 4
      check_interval: 60

# 策略配置
strategy:
  scalping:
    # EMA参数
    ema_fast: 8
    ema_medium: 21
    ema_slow: 55
    
    # 布林带参数
    bb_period: 20
    bb_std: 2.0
    
    # RSI参数
    rsi_period: 14
    rsi_overbought: 75
    rsi_oversold: 25
    
    # MACD参数
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    
    # 随机指标参数
    stoch_k: 14
    stoch_d: 3
    stoch_overbought: 80
    stoch_oversold: 20
    
    # 成交量参数
    volume_ma: 20
    volume_threshold: 1.5
    
    # ATR参数
    atr_period: 14
    atr_multiplier: 2.0
    
    # 信号过滤参数
    min_signal_interval: 3
    trend_filter: true
    volume_filter: true
    volatility_filter: true
    
    # 风险控制参数
    max_risk_per_trade: 0.01
    dynamic_stop_loss: true
    profit_target_ratio: 2.0

# 风险控制配置
risk_control:
  # 资金管理
  initial_capital: 10000
  max_total_risk: 0.05        # 总风险不超过5%
  max_position_size: 0.2      # 单个持仓不超过20%
  max_positions: 3            # 最大同时持仓数
  
  # 止损止盈
  default_stop_loss: 0.02     # 默认止损2%
  default_take_profit: 0.04   # 默认止盈4%
  trailing_stop: true         # 启用移动止损
  trailing_stop_ratio: 0.5    # 移动止损比例
  
  # 时间控制
  max_hold_time: 240          # 最大持仓时间(分钟)
  trading_hours:
    start: "00:00"
    end: "23:59"
    timezone: "UTC"
  
  # 回撤控制
  max_daily_drawdown: 0.03    # 最大日回撤3%
  max_total_drawdown: 0.10    # 最大总回撤10%
  drawdown_pause_time: 60     # 回撤暂停时间(分钟)

# 信号生成配置
signal_generation:
  # 实时监控
  realtime_enabled: true
  websocket_enabled: false    # WebSocket暂时禁用
  
  # 信号过滤
  min_signal_strength: 0.5    # 最小信号强度
  min_confidence: 0.3         # 最小信心度
  max_signals_per_hour: 10    # 每小时最大信号数
  signal_expiry: 300          # 信号过期时间(秒)
  
  # 多时间框架确认
  require_higher_tf_confirm: true   # 需要高时间框架确认
  min_tf_alignment: 0.6            # 最小时间框架一致性
  
  # 信号质量控制
  volume_confirmation: true         # 成交量确认
  trend_alignment_required: true    # 趋势一致性要求
  support_resistance_check: true    # 支撑阻力检查

# 执行配置
execution:
  # 订单类型
  order_type: "market"        # market, limit
  slippage_tolerance: 0.001   # 滑点容忍度
  
  # 执行延迟
  max_execution_delay: 5      # 最大执行延迟(秒)
  retry_attempts: 3           # 重试次数
  retry_delay: 1              # 重试延迟(秒)
  
  # 部分成交
  partial_fill_enabled: true
  min_fill_ratio: 0.8         # 最小成交比例

# 监控配置
monitoring:
  # 性能监控
  performance_update_interval: 60   # 性能更新间隔(秒)
  
  # 日志配置
  log_level: "INFO"
  log_file: "logs/scalping_trading.log"
  max_log_size: "10MB"
  backup_count: 5
  
  # 通知配置
  notifications:
    enabled: true
    channels:
      - type: "console"
        enabled: true
      - type: "file"
        enabled: true
        file: "logs/notifications.log"
      - type: "email"
        enabled: false
        smtp_server: ""
        smtp_port: 587
        username: ""
        password: ""
        to_addresses: []
  
  # 报告配置
  reports:
    daily_report: true
    hourly_stats: true
    trade_summary: true

# 数据配置
data:
  # 数据源
  primary_source: "binance"
  backup_sources: ["okx", "bybit"]
  
  # 数据缓存
  cache_size: 1000            # 缓存大小
  cache_expiry: 300           # 缓存过期时间(秒)
  
  # 历史数据
  preload_periods: 200        # 预加载周期数
  data_validation: true       # 数据验证
  
  # 实时数据
  realtime_buffer_size: 500   # 实时数据缓冲区大小
  data_update_interval: 1     # 数据更新间隔(秒)

# 回测配置
backtest:
  # 回测参数
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_capital: 10000
  
  # 费用设置
  maker_fee: 0.001           # Maker费率
  taker_fee: 0.001           # Taker费率
  
  # 滑点设置
  slippage_model: "linear"   # linear, sqrt, fixed
  slippage_rate: 0.0005      # 滑点率
  
  # 回测输出
  detailed_trades: true
  performance_charts: true
  risk_analysis: true

# 优化配置
optimization:
  # 参数优化
  enabled: false
  method: "grid_search"      # grid_search, random_search, bayesian
  
  # 优化目标
  objective: "sharpe_ratio"  # sharpe_ratio, total_return, max_drawdown
  
  # 优化范围
  parameter_ranges:
    ema_fast: [5, 15, 1]
    ema_medium: [15, 30, 1]
    bb_period: [15, 25, 1]
    rsi_period: [10, 20, 1]
    atr_multiplier: [1.5, 3.0, 0.1]
  
  # 验证设置
  cross_validation: true
  validation_split: 0.3
  walk_forward: true

# 安全配置
security:
  # API安全
  api_key_encryption: true
  rate_limit_buffer: 0.8     # 速率限制缓冲
  
  # 交易安全
  max_order_size: 1000       # 最大订单金额
  daily_loss_limit: 500      # 日亏损限制
  
  # 系统安全
  auto_shutdown_on_error: true
  max_consecutive_losses: 5
  emergency_stop_loss: 0.05  # 紧急止损5%

# 开发配置
development:
  # 调试模式
  debug_mode: false
  verbose_logging: false
  
  # 测试配置
  paper_trading: true        # 模拟交易
  test_data_only: true       # 仅使用测试数据
  
  # 性能分析
  profiling_enabled: false
  memory_monitoring: false
