# TradeFan 策略组合配置示例
# 展示新的策略管理系统配置

version: '2.0.0'
name: 'multi_strategy_portfolio'
description: '多策略组合交易配置'

# 基础配置
api:
  exchange: 'binance'
  api_key: '${BINANCE_API_KEY}'
  api_secret: '${BINANCE_API_SECRET}'
  base_url: 'https://testnet.binance.vision'
  testnet: true

# 交易配置
trading:
  symbols: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT']
  base_currency: 'USDT'
  position_size_ratio: 0.15
  max_positions: 5

# 策略配置
strategies:
  # 趋势跟踪策略
  trend_follower:
    type: 'trend_following'
    enabled: true
    weight: 0.4
    parameters:
      fast_ema: 8
      slow_ema: 21
      rsi_threshold: 50
    timeframes: ['1h', '4h']
    symbols: ['BTCUSDT', 'ETHUSDT']
    risk_settings:
      max_signals_per_hour: 6
      signal_cooldown: 300
      min_signal_strength: 0.3
  
  # 均值回归策略
  mean_reverter:
    type: 'mean_reversion'
    enabled: true
    weight: 0.3
    parameters:
      bb_period: 20
      bb_std: 2.0
      rsi_oversold: 25
      rsi_overbought: 75
      bb_threshold_low: 0.15
      bb_threshold_high: 0.85
    timeframes: ['1h']
    symbols: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT']
    risk_settings:
      max_signals_per_hour: 4
      signal_cooldown: 600
      min_signal_strength: 0.4
  
  # 突破策略
  breakout_trader:
    type: 'breakout'
    enabled: true
    weight: 0.2
    parameters:
      lookback_period: 24
      min_channel_width: 0.025
      volume_confirmation: true
    timeframes: ['4h', '1d']
    symbols: ['BTCUSDT']
    risk_settings:
      max_signals_per_hour: 2
      signal_cooldown: 1800
      min_signal_strength: 0.5
  
  # 动量策略
  momentum_trader:
    type: 'momentum'
    enabled: false  # 可以动态启用/禁用
    weight: 0.1
    parameters:
      momentum_period: 12
      roc_period: 14
      momentum_threshold: 0.025
      rsi_filter: true
      rsi_min: 35
      rsi_max: 65
    timeframes: ['1h']
    symbols: ['ETHUSDT', 'BNBUSDT']
    risk_settings:
      max_signals_per_hour: 8
      signal_cooldown: 300
      min_signal_strength: 0.3

# 策略组合配置
portfolios:
  main_portfolio:
    name: 'Balanced_Multi_Strategy'
    strategies: ['trend_follower', 'mean_reverter', 'breakout_trader']
    weights: [0.5, 0.3, 0.2]
    rebalance_frequency: 'daily'  # daily, weekly, monthly
    
  aggressive_portfolio:
    name: 'High_Frequency_Portfolio'
    strategies: ['trend_follower', 'momentum_trader']
    weights: [0.6, 0.4]
    rebalance_frequency: 'hourly'

# 风险管理
risk_management:
  global_limits:
    max_daily_loss: 0.02
    max_position_risk: 0.008
    max_correlation: 0.7  # 策略间最大相关性
    
  strategy_limits:
    max_concurrent_signals: 3
    signal_conflict_resolution: 'weighted_average'  # first_wins, last_wins, weighted_average
    
  portfolio_limits:
    max_portfolio_exposure: 0.8
    diversification_requirement: 0.3

# 性能监控
monitoring:
  enabled: true
  metrics:
    - 'signal_frequency'
    - 'signal_accuracy'
    - 'strategy_correlation'
    - 'portfolio_performance'
  
  alerts:
    low_performance_threshold: 0.3
    high_correlation_threshold: 0.8
    signal_frequency_anomaly: 2.0  # 标准差倍数
  
  reporting:
    daily_report: true
    weekly_summary: true
    performance_comparison: true

# 数据管理
data_management:
  cache_strategy_data: true
  cache_duration: 3600  # 秒
  data_validation: true
  missing_data_handling: 'interpolate'  # skip, interpolate, use_last

# 执行设置
execution:
  signal_aggregation: 'weighted_average'
  minimum_signal_strength: 0.2
  signal_timeout: 300  # 秒
  
  order_management:
    order_type: 'market'
    slippage_tolerance: 0.001
    partial_fill_handling: 'accept'

# 日志配置
logging:
  strategy_logs: true
  signal_logs: true
  performance_logs: true
  
  log_levels:
    strategy_manager: 'INFO'
    individual_strategies: 'DEBUG'
    portfolio_manager: 'INFO'
  
  structured_logging: true
  export_signals: true
