# TradeFan 测试网络配置
# 6小时测试环境配置

# API配置 - 测试环境
api:
  exchange: "binance"
  environment: "testnet"  # 测试网络
  api_key: "36435953f329745c711efa0440f19e95d264b1298cc0c1f2d2241f4c92f69209"
  api_secret: "19ebb309301c2127b39f68591b685d97d76e2d89142c21694c660e1c73334a6c"
  base_url: "https://testnet.binance.vision"  # 测试网络URL
  
# 测试配置
test_config:
  duration_hours: 6
  start_time: "auto"  # 自动开始
  test_mode: true
  paper_trading: false  # 使用真实测试网络
  
# 交易配置 - 测试环境
trading:
  initial_capital: 1000  # 测试资金
  max_positions: 2  # 限制持仓数量
  symbols:
    - symbol: "BTCUSDT"
      enabled: true
      allocation: 0.4
    - symbol: "ETHUSDT" 
      enabled: true
      allocation: 0.3
    - symbol: "BNBUSDT"
      enabled: true
      allocation: 0.3
      
  timeframes:
    - "5m"
    - "15m"
    - "1h"

# 风险控制 - 保守测试参数
risk_control:
  max_risk_per_trade: 0.02  # 2%单笔风险
  max_daily_loss: 0.05      # 5%日最大亏损
  max_total_loss: 0.10      # 10%总最大亏损
  stop_loss_atr_multiplier: 2.0
  take_profit_ratio: 2.0    # 2:1盈亏比
  max_position_time_hours: 4

# 策略配置 - 双策略测试
strategies:
  scalping:
    enabled: true
    weight: 0.6
    parameters:
      ema_fast: 8
      ema_medium: 21
      ema_slow: 55
      bb_period: 20
      bb_std: 2.0
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      
  trend_following:
    enabled: true
    weight: 0.4
    parameters:
      ema_periods: [21, 55, 200]
      adx_period: 14
      adx_threshold: 25
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9

# 监控配置
monitoring:
  log_level: "INFO"
  save_trades: true
  real_time_updates: true
  alert_on_loss: true
  alert_threshold: 0.03  # 3%亏损时告警
  
# 测试报告
reporting:
  generate_report: true
  report_interval_minutes: 30
  save_charts: true
  performance_metrics: true
